# Generated by Django 5.2.6 on 2025-09-25 23:15

import visitscrudapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(validators=[visitscrudapp.models.validate_rating])),
            ],
        ),
    ]
